### ISSUE TITLE
custom domain

### ISSUE THREAD

**Issue by u0nel** [asozialesnetzwerk/asozialesnetzwerk.github.io#5]
Also ich hab u1l.de und würde gerne an.u1l.de als custom domain für github pages setzen, weil ich keine lust hab immer asozialesnetzwerk.github.io zu tippen.

**Comment by Joshix-1** [comment]
dann mach

**Comment by Joshix-1** [comment]
![image](https://user-images.githubusercontent.com/57299889/108902548-8b1c9480-761c-11eb-8f46-2012da681689.png)

**Comment by Joshix-1** [comment]
leite von deiner Seite lieber auf die github.io-Seite weiter. Wäre glaube ich einfacher.

**Comment by u0nel** [comment]
ok hab jetzt dns auf asozialesnetzwerk.github.io gesetzt

**Comment by Guerteltier** [comment]
> leite von deiner Seite lieber auf die github.io-Seite weiter. Wäre glaube ich einfacher.

Inwiefern ist etwas, das in DNS unmöglich ist einfacher als einen CNAME-Eintrag zu erstellen? WTF

**Bald:tm:** haben wir aber sowieso **asozial.org**...

**Comment by Joshix-1** [comment]
Wann ist **Bald**™?

**Comment by Guerteltier** [comment]
**Sehr Bald™**

**Comment by u0nel** [comment]
scheint jetzt zu funktionieren

**Comment by u0nel** [comment]
also weil asozial und an.u1l.de jetzt gehen, mach ich schließe ich das issue
